### ISSUE TITLE
Angle Marker Syling

### ISSUE THREAD

**Issue by dickinson0718** [dulimarta/spherical-easel#78] opened 2024-07-09 17:19 UTC
Create and select an angle marker..

1) open the front subpanel and the anglemarker tab. Scale the angle marker as large as possible. The label on the largest scale is `NaN` (but the angle marker does scale)

2) I forgot what "Front & Back" and "Front | Back" means on our [styling property matrix](https://docs.google.com/spreadsheets/d/1LCU76H19DUIT_MjdPwh8twhwO8DAFVQYwtgXo194iMw/edit?gid=0#gid=0) in the angle marker section. So I'm sorry if I have not communicated well about this. Because tick mark, arrow heads, and double mark an angle (and it doesn't matter if that angle is on the front or back) either the controls for these three items should be removed from the back sub-panel in the angle marker tab or the adjusting these three items in the back sub-panel in the angle marker tab should control both the display and the front (i.e. changing any of these three on the front or back effect the display and the switches on the other sub-panel anglemarker tab).

3) The radius of the angle marker on the back (when *not* inferred from the the front) should be independent of the front. (i.e. radius of angle marker should behave like fill when not inferred from the front -- front and back are independently controled)

**Comment by dulimarta** [comment] 2024-08-01 16:14
I was not able to reproduce #1. The label shows 200%.

![Screenshot 2024-08-01 120755](https://github.com/user-attachments/assets/f7274a55-095d-489d-a05d-b7435291cb0b)

**Comment by dickinson0718** [comment] 2024-08-01 16:25
Interesting! I get NaN. I'm in the export-svg branch

<img width="1425" alt="Screenshot 2024-08-01 at 12 24 02 PM" src="https://github.com/user-attachments/assets/5c7b8379-57b6-4edc-a32e-a848457650cd">

**Comment by dickinson0718** [comment] 2024-08-01 16:28
Oh! Hang on I was wrong in #1, I mean the radius of the angle marker, not the scale of the label. Sorry!

**Comment by dulimarta** [comment] 2024-08-01 16:30
Issue (2) & (3) are fixed by adding more `v-if` in `FrontBackStyle.vue` so the Angle marker tab on the Back substyle shows only the radius slider.

**Comment by dulimarta** [comment] 2024-08-02 12:52
Issue (1) is cause by an incorrect comparison operator when building the array of string labels (at around line 450).

```
for (let s = 0; s < maxPercent; s += 20) // the bad code
```

```
for (let s = 0; s <= maxPercent; s += 20) // the fix
```

**Closed by dulimarta** 2024-08-02 12:52 UTC
