### ISSUE TITLE
tool hints:  quickly disappear

### ISSUE THREAD

**Issue by don-sp** [dulimarta/spherical-easel#2] opened 2021-09-25 04:41 UTC
This issue is with the text that pops up when a tool is clicked. The text boxes appear for a second only, even though they have what looks like a delete "X," suggesting they will display until dismissed.

**Comment by don-sp** [comment] 2021-09-25 08:25
A correction -- this issue is with the text that pops up when a tool is clicked.  The text boxes appear for a second only, even though they have what looks like a delete "X," suggesting they will display until dismissed.

**Comment by dickinson0718** [comment] 2021-11-14 23:08
Closing as a duplicate of issue #23

**Closed by dickinson0718** 2021-11-14 23:08 UTC
