### ISSUE TITLE
Create Measurement from Slider

### ISSUE THREAD

**Issue by MCBailey-CTS** [dulimarta/spherical-easel#14] opened 2021-11-14 14:12 UTC
**Heuristic:**\
3 User control and freedom\
5 Error prevention\
**Severity:** 4\
**Problem:** When a MEASUREMENT object is created using the "Create" button in the "SLIDER" drop down, there is no delete button, and therefore no way to delete it.\
**Solution:** Add a delete button to the MEASUREMENT object.

**Comment by dickinson0718** [comment] 2021-11-14 23:11
Closing as a duplicate of issue #16

**Closed by dickinson0718** 2021-11-14 23:11 UTC
