### ISSUE TITLE
Exiting out of Tools

### ISSUE THREAD

**Issue by MCBailey-CTS** [dulimarta/spherical-easel#11] opened 2021-11-14 14:08 UTC
**Heuristic:** 3 User control and freedom

**Severity:** 3

**Problem:**\
When clicking any tool button,
unless the user manages to click the orange X in the lower left pane before it disappears\
(which is about 2 seconds), there is no apparent way to exit out of the tool.\
The only to way to exit is to either click another control,\
which immediately launches that control, or re click the original tool\
again and then click the orange X as it reappears again for a few seconds.\

**Solution:** Leave the black and orange pane with the cancel X open indefinitely until the user 
              physically clicks it, or allow the user hit the "esc" key which also exits the current tool event.

**Comment by dickinson0718** [comment] 2021-11-14 20:40
This is a issue with the snackbar and eventbus message display time and this is something we definitely need to redesign.

**Comment by dickinson0718** [comment] 2021-11-14 23:08
Closing as a duplicate of issue #23

**Closed by dickinson0718** 2021-11-14 23:08 UTC
